all: homework9

homework9: main.o pokemon.o lickitung.o sunkern.o unown.o
	g++ -o homework9 main.o pokemon.o lickitung.o sunkern.o unown.o

main.o: main.cpp 
	g++ -ansi -pedantic-errors -Wall -c main.cpp

pokemon.o: pokemon.cpp 
	g++ -ansi -pedantic-errors -Wall -c pokemon.cpp

lickitung.o: lickitung.cpp 
	g++ -ansi -pedantic-errors -Wall -c lickitung.cpp

sunkren.o: sunkern.cpp 
	g++ -ansi -pedantic-errors -Wall -c sunkern.cpp

unown.o: unown.cpp
	g++ -ansi -pedantic-errors -Wall -c unown.cpp
